"""Build the golden set: hand-authored questions -> resolved, chunk-addressed labels.

    python3 build.py            # writes golden-set.v1.jsonl + golden-set.v1.manifest.json
    python3 build.py --check    # resolves everything, writes nothing, exits 1 on drift

The output is a *derived artifact*. It is committed so reviewers can read it and so
exercise 2 can consume it without a build step, but it is never edited by hand: the
source of truth is questions.jsonl, and this file can be regenerated byte-identically
from it at any time. That is the success criterion in 00 §16 exercise 1 — "you can
regenerate the file deterministically if the corpus is re-chunked."
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from chunker import CHUNKER_VERSION, MAX_CHARS, chunk_corpus
from corpus import CANONICAL_VERSION, corpus_digest, load_corpus
from goldenset import LocatorError, chunks_for_span, load_questions, resolve_locator, union_coverage

HERE = Path(__file__).resolve().parent
CORPUS_ROOT = HERE.parent.parent  # ai-rag/
QUESTIONS = HERE / "questions.jsonl"
OUT_JSONL = HERE / "golden-set.v1.jsonl"
OUT_MANIFEST = HERE / "golden-set.v1.manifest.json"

# The hit rule used to derive answer_bearing_chunk_ids. Written into the manifest,
# because a recall number computed under a different rule is a different number
# (02 §11.2) and the two must never be compared.
BUILD_HIT_RULE = "any_overlap"


def corpus_commit(root: Path) -> str:
    """Best-effort git provenance. Unknown is acceptable; wrong is not."""
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return out.stdout.strip() if out.returncode == 0 else "unknown"
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def build() -> tuple[list[dict], dict]:
    docs = load_corpus(CORPUS_ROOT)
    chunks = chunk_corpus(docs)
    questions = load_questions(QUESTIONS)

    by_doc: dict[str, list] = {}
    for c in chunks:
        by_doc.setdefault(c.doc_id, []).append(c)

    records: list[dict] = []
    errors: list[str] = []
    seen_ids: set[str] = set()

    for q in questions:
        if q.id in seen_ids:
            errors.append(f"{q.id}: duplicate question id")
            continue
        seen_ids.add(q.id)

        spans, chunk_ids, per_span = [], [], []
        try:
            for loc in q.locators:
                span = resolve_locator(docs, loc)
                hit = chunks_for_span(by_doc.get(span.doc_id, []), span, BUILD_HIT_RULE)
                if not hit:
                    raise LocatorError(f"{q.id}: span resolved but matched no chunk — chunker bug")
                spans.append(span)
                per_span.append(round(union_coverage(hit, span), 4))
                chunk_ids.extend(c.chunk_id for c in hit)
        except LocatorError as exc:
            errors.append(str(exc))
            continue

        records.append(
            {
                # The three fields 00 §16 exercise 1 asks for, first and unqualified.
                "query": q.query,
                "answer_bearing_chunk_ids": sorted(dict.fromkeys(chunk_ids)),
                "expected_answer": q.expected_answer,
                # Everything below is provenance: what makes the record reproducible,
                # reviewable, and re-derivable after a re-chunk.
                "query_id": q.id,
                "hop": q.hop,
                "tags": list(q.tags),
                "answer_spans": [
                    {"doc_id": s.doc_id, "char_start": s.char_start, "char_end": s.char_end}
                    for s in spans
                ],
                "span_union_coverage": per_span,
                "chunker_version": CHUNKER_VERSION,
                "canonical_version": CANONICAL_VERSION,
            }
        )

    if errors:
        for e in errors:
            print(f"ERROR {e}", file=sys.stderr)
        raise SystemExit(f"{len(errors)} unresolved record(s); refusing to write a partial golden set")

    manifest = {
        "n_records": len(records),
        "n_chunks": len(chunks),
        "n_docs": len(docs),
        "corpus_chars": sum(len(d) for d in docs.values()),
        "corpus_digest": corpus_digest(docs),
        "corpus_commit": corpus_commit(CORPUS_ROOT),
        "chunker_version": CHUNKER_VERSION,
        "canonical_version": CANONICAL_VERSION,
        "max_chars": MAX_CHARS,
        "build_hit_rule": BUILD_HIT_RULE,
        "docs": {doc_id: {"sha256": d.sha256, "chars": len(d)} for doc_id, d in sorted(docs.items())},
    }
    return records, manifest


def serialize(records: list[dict], manifest: dict) -> tuple[str, str]:
    body = "".join(json.dumps(r, ensure_ascii=False, sort_keys=True) + "\n" for r in records)
    meta = json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    return body, meta


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify only; write nothing")
    args = ap.parse_args()

    records, manifest = build()
    body, meta = serialize(records, manifest)

    if args.check:
        stale = []
        if not OUT_JSONL.exists() or OUT_JSONL.read_text(encoding="utf-8") != body:
            stale.append(OUT_JSONL.name)
        # corpus_commit moves on every commit and is deliberately excluded from the
        # drift check: it is provenance, not content.
        if OUT_MANIFEST.exists():
            old = json.loads(OUT_MANIFEST.read_text(encoding="utf-8"))
            if {k: v for k, v in old.items() if k != "corpus_commit"} != {
                k: v for k, v in manifest.items() if k != "corpus_commit"
            }:
                stale.append(OUT_MANIFEST.name)
        else:
            stale.append(OUT_MANIFEST.name)
        if stale:
            raise SystemExit(f"stale artifact(s): {', '.join(stale)} — run `python3 build.py`")
        print(f"OK  {len(records)} records, {manifest['n_chunks']} chunks, artifacts current")
        return

    OUT_JSONL.write_text(body, encoding="utf-8")
    OUT_MANIFEST.write_text(meta, encoding="utf-8")
    multi = sum(1 for r in records if r["hop"] == "multi")
    print(
        f"wrote {OUT_JSONL.name}: {len(records)} records "
        f"({multi} multi-hop) over {manifest['n_chunks']} chunks / {manifest['n_docs']} docs"
    )


if __name__ == "__main__":
    main()
